import React, { useState, useEffect } from 'react'
import { FileText, Download, Printer, Plus, Calendar, ChevronRight, CheckCircle } from 'lucide-react'
import { useDataset } from '../context/DatasetContext'
import toast from 'react-hot-toast'

const Reports = () => {
  const { activeDataset, isUploaded } = useDataset()
  const [reportType, setReportType] = useState('daily')
  const [reports, setReports] = useState([
    { id: 1, name: 'Daily Operations Report', date: new Date().toISOString().slice(0, 10), status: 'Ready', size: '2.4 MB', type: 'daily' },
    { id: 2, name: 'Weekly Performance Summary', date: '2026-08-28', status: 'Ready', size: '3.1 MB', type: 'weekly' },
    { id: 3, name: 'Monthly Risk Assessment', date: '2026-08-15', status: 'Ready', size: '5.8 MB', type: 'monthly' },
    { id: 4, name: 'Q3 Predictive Analysis', date: '2026-07-01', status: 'Ready', size: '12.3 MB', type: 'quarterly' }
  ])

  const reportTypes = [
    { id: 'daily', label: 'Daily Report' },
    { id: 'weekly', label: 'Weekly Report' },
    { id: 'monthly', label: 'Monthly Report' },
    { id: 'quarterly', label: 'Quarterly Report' },
    { id: 'custom', label: 'Custom Report' }
  ]

  const handleGenerateReport = () => {
    toast.loading('Generating management report...')
    setTimeout(() => {
      const typeObj = reportTypes.find(t => t.id === reportType) || { label: 'Custom Report' }
      const newRep = {
        id: Date.now(),
        name: `${typeObj.label} - ${isUploaded ? activeDataset?.file?.name || 'Dataset' : 'System Overview'}`,
        date: new Date().toISOString().slice(0, 10),
        status: 'Ready',
        size: '2.8 MB',
        type: reportType
      }
      setReports(prev => [newRep, ...prev])
      toast.dismiss()
      toast.success(`${typeObj.label} generated successfully!`)
    }, 600)
  }

  const handleDownloadReportItem = (report) => {
    const totalOps = isUploaded && activeDataset?.kpis?.totalOperations?.value ? activeDataset.kpis.totalOperations.value : 12480
    const activeRes = isUploaded && activeDataset?.kpis?.activeResources?.value ? activeDataset.kpis.activeResources.value : 8742
    const riskAlerts = isUploaded && activeDataset?.kpis?.riskAlerts?.value ? activeDataset.kpis.riskAlerts.value : 27
    const accuracy = isUploaded && activeDataset?.kpis?.forecastAccuracy?.value ? activeDataset.kpis.forecastAccuracy.value : 94.8

    const content = `PREDICTIVE MANAGEMENT SYSTEM - ${report.name.toUpperCase()}
Date: ${report.date}
Status: ${report.status}

=== EXECUTIVE KPI SUMMARY ===
- Total Operations: ${totalOps}
- Active Resources: ${activeRes}
- Risk Alerts: ${riskAlerts}
- Forecast Model Accuracy: ${accuracy}%

=== KEY INSIGHTS & TELEMETRY ===
1. ${activeDataset?.insight || 'Operational demand trajectory aligns with forecasted baseline expectations.'}
2. Resource capacity utilization is actively monitored across all departments.
3. Automated anomaly detection algorithms report normal variance limits.

Generated by PrescientIQ — Autonomous Predictive Intelligence Platform.
`
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-${report.date}.txt`
    document.body.appendChild(a)
    a.click()
    a.remove()
    toast.success(`Downloaded ${report.name}`)
  }

  const handlePrintReport = (report) => {
    toast.success(`Preparing ${report.name} for print...`)
    window.print()
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold text-secondary-900">Reports Center</h1>
          <p className="text-secondary-500 mt-1">Generate, view, and export executive management reports</p>
        </div>
        <button onClick={handleGenerateReport} className="btn-primary text-sm flex items-center gap-2">
          <Plus size={16} />
          Generate Report
        </button>
      </div>

      {/* Report Types */}
      <div className="card p-4 flex flex-wrap gap-2">
        {reportTypes.map((type) => (
          <button
            key={type.id}
            onClick={() => setReportType(type.id)}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
              reportType === type.id
                ? 'bg-primary-500 text-white shadow-sm'
                : 'bg-gray-100 text-secondary-600 hover:bg-gray-200'
            }`}
          >
            {type.label}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Report List */}
        <div className="lg:col-span-2 card overflow-hidden">
          <div className="p-4 border-b border-gray-100 flex items-center justify-between">
            <h3 className="font-semibold text-secondary-900">Generated Reports</h3>
            <span className="text-xs text-secondary-500">{reports.length} Reports Available</span>
          </div>
          <div className="divide-y divide-gray-100">
            {reports.map((report) => (
              <div key={report.id} className="p-4 hover:bg-gray-50 flex items-center justify-between transition-colors">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-primary-100 rounded-lg flex items-center justify-center">
                    <FileText className="w-5 h-5 text-primary-600" />
                  </div>
                  <div>
                    <p className="font-medium text-secondary-900">{report.name}</p>
                    <div className="flex items-center gap-3 text-sm text-secondary-500 mt-0.5">
                      <span>{report.date}</span>
                      <span>{report.size}</span>
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                        report.status === 'Ready' ? 'bg-primary-100 text-primary-700' : 'bg-yellow-100 text-yellow-700'
                      }`}>
                        {report.status}
                      </span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <button 
                    onClick={() => handleDownloadReportItem(report)}
                    className="p-2 rounded-lg hover:bg-gray-200 text-secondary-600 transition-colors"
                    title="Download Report"
                  >
                    <Download size={16} />
                  </button>
                  <button 
                    onClick={() => handlePrintReport(report)}
                    className="p-2 rounded-lg hover:bg-gray-200 text-secondary-600 transition-colors"
                    title="Print Report"
                  >
                    <Printer size={16} />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Report Preview */}
        <div className="card p-6 space-y-4">
          <h3 className="font-semibold text-secondary-900">Active Dataset Preview</h3>
          <div className="bg-gray-50 p-4 rounded-lg">
            <p className="text-sm font-medium text-secondary-700">KPI Summary</p>
            <div className="mt-2 space-y-1 text-sm text-secondary-600">
              <p>• Total Operations: {isUploaded && activeDataset?.kpis?.totalOperations?.value ? activeDataset.kpis.totalOperations.value : '12,480'}</p>
              <p>• Active Resources: {isUploaded && activeDataset?.kpis?.activeResources?.value ? activeDataset.kpis.activeResources.value : '8,742'}</p>
              <p>• Risk Alerts: {isUploaded && activeDataset?.kpis?.riskAlerts?.value ? activeDataset.kpis.riskAlerts.value : '27'}</p>
              <p>• Forecast Accuracy: {isUploaded && activeDataset?.kpis?.forecastAccuracy?.value ? activeDataset.kpis.forecastAccuracy.value : '94.8'}%</p>
            </div>
          </div>
          <div className="bg-gray-50 p-4 rounded-lg">
            <p className="text-sm font-medium text-secondary-700">Key Insights</p>
            <ul className="mt-2 space-y-1 text-sm text-secondary-600 list-disc list-inside">
              <li>{activeDataset?.insight || 'Demand expected to increase 18%'}</li>
              <li>Resource utilization balance optimized</li>
              <li>Predictive model confidence high</li>
            </ul>
          </div>
          <button onClick={handleGenerateReport} className="w-full btn-primary text-sm">
            Generate Full Report
          </button>
        </div>
      </div>
    </div>
  )
}

export default Reports